// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// OGDevice
void OGDevice(double width, double height, double pointsize, std::string font);
RcppExport SEXP _ROfficeGraphics_OGDevice(SEXP widthSEXP, SEXP heightSEXP, SEXP pointsizeSEXP, SEXP fontSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type width(widthSEXP);
    Rcpp::traits::input_parameter< double >::type height(heightSEXP);
    Rcpp::traits::input_parameter< double >::type pointsize(pointsizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type font(fontSEXP);
    OGDevice(width, height, pointsize, font);
    return R_NilValue;
END_RCPP
}
// ZipAndSendToClipboard
void ZipAndSendToClipboard(Rcpp::Environment archive);
RcppExport SEXP _ROfficeGraphics_ZipAndSendToClipboard(SEXP archiveSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type archive(archiveSEXP);
    ZipAndSendToClipboard(archive);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ROfficeGraphics_OGDevice", (DL_FUNC) &_ROfficeGraphics_OGDevice, 4},
    {"_ROfficeGraphics_ZipAndSendToClipboard", (DL_FUNC) &_ROfficeGraphics_ZipAndSendToClipboard, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ROfficeGraphics(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
