// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ZipAndSendToClipboard
void ZipAndSendToClipboard(Rcpp::Environment archive);
RcppExport SEXP _RDrawingML_ZipAndSendToClipboard(SEXP archiveSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type archive(archiveSEXP);
    ZipAndSendToClipboard(archive);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RDrawingML_ZipAndSendToClipboard", (DL_FUNC) &_RDrawingML_ZipAndSendToClipboard, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RDrawingML(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
